@startuml
hide circle
skinparam classAttributeIconSize 0

class Developer {
  +name: String
  +traits: List<Trait>
  +addTrait(trait: Trait)
  +showTraits()
}

class Trait {
  +name: String
  +description: String
}

class Collaboration extends Trait
class ProblemSolving extends Trait
class Adaptability extends Trait

Developer "1" *-- "*" Trait
@enduml